In [91]:
import numpy as np

In [92]:
a = np.array([1,2,3]) #one dimension

In [93]:
a

array([1, 2, 3])

In [94]:
a.shape

(3,)

In [95]:
a.size

3

In [96]:
a.ndim

1

In [97]:
b = np.array([[1,2,3],[2,3,4]]) #2 dimensional arrays 

In [98]:
print(b)

[[1 2 3]
 [2 3 4]]


In [99]:
b.shape

(2, 3)

In [100]:
b.size

6

In [101]:
b.ndim

2

In [102]:
b.dtype

dtype('int32')

In [103]:
c = np.array([[1,2,3],[3,4,5],[4,5,6], [4,5,6]])

In [104]:
print(c)

[[1 2 3]
 [3 4 5]
 [4 5 6]
 [4 5 6]]


In [105]:
c.shape

(4, 3)

In [106]:
c.size

12

In [107]:
c.ndim

2

In [108]:
c.size * a.itemsize

48

### Getting specifi elements

In [109]:
d = np.array([[1,2,3,4,5,6,7], [4,5,6,7,8,9,10]])

In [110]:
print(d)

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


In [111]:
d[0,-1]

7

In [112]:
d[1, 5:]

array([ 9, 10])

In [113]:
d[0]

array([1, 2, 3, 4, 5, 6, 7])

In [114]:
d[0,4]

5

In [115]:
d[:, 3]

array([4, 7])

## Getting a little more fancy

In [116]:
#start index, end index and step index
print(d)

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


In [117]:
d[0, 1:6:2]

array([2, 4, 6])

In [118]:
d[1, 1:6:3]

array([5, 8])

In [119]:
d[1, 5] = 5

In [120]:
d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8,  5, 10]])

In [121]:
d[0,5] = 200

In [122]:
d

array([[  1,   2,   3,   4,   5, 200,   7],
       [  4,   5,   6,   7,   8,   5,  10]])

In [123]:
f = np.array([[[1,2,3],[3,5,6]],[[6,4,2],[6,5,9]]])

In [124]:
f

array([[[1, 2, 3],
        [3, 5, 6]],

       [[6, 4, 2],
        [6, 5, 9]]])

In [125]:
f.ndim

3

In [126]:
f.shape

(2, 2, 3)

In [127]:
f[1,0,2]

2

### Initializing different types of arrays

In [128]:
#all 0s matrix
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [129]:
np.ones((3,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [130]:
np.full((3,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [131]:
##matrix of random numbers
p = np.random.rand(2,3)

In [132]:
p

array([[0.9018833 , 0.61072597, 0.81255541],
       [0.21010618, 0.13775686, 0.4843165 ]])

In [133]:
h = np.array([[2,3,4], [2,5,6]])

In [134]:
h

array([[2, 3, 4],
       [2, 5, 6]])

In [135]:
np.random.rand(2,3)

array([[0.61222962, 0.47669941, 0.65745543],
       [0.9868588 , 0.03855456, 0.19399622]])

In [148]:
#Identity Matrix
a = np.identity(4)

In [149]:
a.dtype

dtype('float64')

In [150]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [172]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 4, axis = 0)

In [173]:
arr

array([[1, 2, 3]])

In [174]:
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [175]:
r1.shape

(4, 3)

In [176]:
r1.ndim

2

In [177]:
r1.size

12

In [191]:
output = np.ones((5,5))

In [192]:
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [196]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [204]:
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [211]:
output[1: -1, 1: -1] = z

In [212]:
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [219]:
a = np.array ([1,2,3])
b = a.copy()
b[0] = 100

In [220]:
print(a)

[1 2 3]


In [221]:
print(b)

[100   2   3]


In [222]:
a

array([1, 2, 3])

#### USING NUMPY TO DO ARITHMETIC

In [223]:
a = np.array([1,2,3,4])

In [224]:
print(a)

[1 2 3 4]


In [225]:
a*2

array([2, 4, 6, 8])

In [226]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [227]:
a-2

array([-1,  0,  1,  2])

In [228]:
a

array([1, 2, 3, 4])

In [229]:
b = np.array([3,4,5,6])

In [230]:
a +b

array([ 4,  6,  8, 10])

In [231]:
a*b

array([ 3,  8, 15, 24])

In [232]:
b**a

array([   3,   16,  125, 1296], dtype=int32)

In [233]:
a**a

array([  1,   4,  27, 256], dtype=int32)

In [236]:
print(a)
print(b)

[1 2 3 4]
[3 4 5 6]


### To take the sin/cos of the values

In [241]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [242]:
np.sin(b)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [243]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [244]:
np.cos(b)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

### Linear Algebra

In [255]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

#in linear algebra, you will have to ensure that the row of the one matrix is equal to the column of the other matrix

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [256]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [266]:
c = np.identity(2)

In [267]:
print(c)

[[1. 0.]
 [0. 1.]]


In [268]:
np.linalg.det(c) #linear algebra

1.0

In [281]:
d = np.full((4,4), 1)

In [282]:
d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [283]:
np.linalg.det(d)

0.0

## Statistics

In [286]:
#Min, Max and #sum

stats = np.array([[2,3,4], [4,5,6]])

In [287]:
stats

array([[2, 3, 4],
       [4, 5, 6]])

In [299]:
stats.min() #minimum value is the matrix

2

In [301]:
stats.max() #maximum value in the matrix

6

In [293]:
np.max(stats)#another way of achieving it

6

In [300]:
stats.sum() #sum of the matrix

24

### Reorganizing Arrays

In [302]:
before = np.array([[2,3,4], [4,5,6]])

In [303]:
print(before)

[[2 3 4]
 [4 5 6]]


In [304]:
before.shape

(2, 3)

In [308]:
after = before.reshape((6,1)) #reshaping the matrix

In [310]:
after

array([[2],
       [3],
       [4],
       [4],
       [5],
       [6]])

In [313]:
after_ = before.reshape((3,2))

In [314]:
after_

array([[2, 3],
       [4, 4],
       [5, 6]])

### Vertical Stacking vectors

In [316]:
v1 = np.array([1,2,3,4])
v2 = np.array([3,6,8,4])

np.vstack([v1,v2, v1, v2]) #stacking vertically

array([[1, 2, 3, 4],
       [3, 6, 8, 4],
       [1, 2, 3, 4],
       [3, 6, 8, 4]])

In [317]:
h1 = ([1,2])
h2 = ([2,4])

np.hstack([h1,h2]) #horizontal stacking

array([1, 2, 2, 4])

In [318]:
np.hstack([v1,v2]) #horizontal stacking

array([1, 2, 3, 4, 3, 6, 8, 4])

### ADVANCED INDEXING AND BOOLEAN MASKING

In [320]:
a = np.array([[1,2,3], [5,7,4], [4,3,8]])

In [322]:
print(a)

[[1 2 3]
 [5 7 4]
 [4 3 8]]


In [333]:
a[a>4] #boolean values 

array([5, 7, 8])

In [326]:
a > 4 #boolean, true or false

array([[False, False, False],
       [ True,  True, False],
       [False, False,  True]])

In [334]:
##you can get index with a list in numpy
list_ = np.array([1,2,3,4,5,6,7,8,9])
list_[[2,4,6]]

array([3, 5, 7])

In [335]:
print(list_[[5,2,1]])

[6 3 2]


In [339]:
np.any(a > 4, axis=1) #to check boolean values in row

array([False,  True,  True])

In [346]:
a

array([[1, 2, 3],
       [5, 7, 4],
       [4, 3, 8]])

In [347]:
np.any(a > 4, axis=0) #to check boolean values in coulumn

array([ True,  True,  True])

In [349]:
np.all(a > 4, axis=0)

array([False, False, False])

In [353]:
np.any(a/4, axis=1)

array([ True,  True,  True])

In [354]:
((a > 4) & (a <= 4))

array([[False, False, False],
       [False, False, False],
       [False, False, False]])